// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func indexPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>go-sse × DataStar</title><link rel=\"stylesheet\" href=\"/static/styles.css\"><script type=\"module\" src=\"/static/datastar.js\"></script></head><body><main class=\"card\"><div data-signals=\"{progress: 0}\"><h1>go-sse × DataStar</h1><p class=\"subtitle\">Live <strong>Server-Sent Events</strong> from a Go backend powered by <code>github.com/larsartmann/go-sse</code>, rendered with <a href=\"https://data-star.dev\">DataStar</a>. No frontend JavaScript required.</p><button data-on:click=\"@get('/events')\">Restart demo</button><div data-init=\"@get('/events')\"></div><div class=\"progress-bar\"><div class=\"progress-fill\" data-style:width=\"$progress + '%'\"></div></div><div class=\"status\" id=\"status\"><p>Connecting…</p></div><p class=\"signal-value\">Signal value: <span data-text=\"$progress\"></span>%</p></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
