// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func indexPage(alertsOnly bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>go-sse × DataStar — Live Activity Feed</title><meta property=\"og:title\" content=\"go-sse × DataStar — Live Activity Feed\"><meta property=\"og:description\" content=\"Server-Sent Events transport for Go with live fan-out, filtering, and reconnection replay.\"><meta property=\"og:type\" content=\"website\"><link rel=\"icon\" href=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%E2%9A%A1%3C/text%3E%3C/svg%3E\"><link rel=\"stylesheet\" href=\"/static/styles.css\"><script type=\"module\" src=\"/static/datastar.js\"></script><script src=\"/static/app.js\" defer></script></head><body><main class=\"card\"><div data-signals=\"{subscriberCount: 0, replayed: 0, totalEvents: 0, paused: false}\"><header class=\"card__header\"><div class=\"header-row\"><h1>go-sse × DataStar</h1><button class=\"theme-toggle\"><span class=\"theme-toggle__dark\">Dark</span> <span class=\"theme-toggle__light\">Light</span></button></div><p class=\"subtitle\">Live activity feed powered by Server-Sent Events. Open multiple tabs to see real-time fan-out — every tab receives the same events simultaneously.</p></header><nav class=\"filter-bar\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if alertsOnly {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a class=\"filter-bar__link\" href=\"/\">All events</a> <span class=\"filter-bar__active\">Alerts only</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"filter-bar__active\">All events</span> <a class=\"filter-bar__link\" href=\"/?filter=alerts\">Alerts only</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span class=\"filter-bar__hint\">press 'a' for alerts</span></nav><div class=\"stats-bar\"><div class=\"stat\"><span class=\"stat__value\" data-text=\"$subscriberCount\"></span> <span class=\"stat__label\">clients connected</span></div><div class=\"stat\"><span class=\"stat__value\" data-text=\"$totalEvents\"></span> <span class=\"stat__label\">events sent</span></div><div class=\"stat stat--live\"><span class=\"live-dot\"></span> <span class=\"stat__label\">live</span></div></div><div class=\"replay-banner\" data-show=\"$replayed > 0\">Replayed <span data-text=\"$replayed\"></span> missed events on reconnect</div><div class=\"feed-controls\"><button class=\"feed-controls__btn\" data-on-click=\"@set('paused', !$paused)\"><span data-show=\"!$paused\">Pause</span> <span data-show=\"$paused\">Resume</span></button></div><div class=\"feed-empty\" data-show=\"$totalEvents === 0 && !$paused\">Waiting for events…</div><div class=\"feed-paused\" data-show=\"$paused\">Paused — updates will appear on resume</div><div class=\"feed\" id=\"feed\" data-show=\"$totalEvents > 0 && !$paused\"></div><footer class=\"card__footer\"><p>Powered by <code>github.com/larsartmann/go-sse</code>. Events fan out via <code>Broadcaster</code>, replay via <code>EventStore</code>, filtering via <code>SubscribeFilter</code>, keep-alive via <code>Heartbeat</code>.</p></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if alertsOnly {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div data-init=\"@get('/events?filter=alerts')\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div data-init=\"@get('/events')\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
